# Generated by Django 4.0.2 on 2022-02-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=200)),
                ('c2', models.CharField(max_length=200)),
                ('c3', models.CharField(max_length=200)),
                ('c4', models.CharField(max_length=200)),
                ('c5', models.CharField(max_length=200)),
                ('c6', models.CharField(max_length=200)),
                ('c7', models.CharField(max_length=200)),
                ('c8', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mediaForm/')),
                ('upload_date', models.DateTimeField()),
                ('sessionData', models.CharField(max_length=1000)),
            ],
        ),
    ]
