# Generated by Django 3.2.11 on 2022-02-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mediaForm/')),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('sessionData', models.CharField(max_length=1000)),
                ('c1', models.CharField(blank=True, max_length=200, null=True)),
                ('c2', models.CharField(blank=True, max_length=200, null=True)),
                ('c3', models.CharField(blank=True, max_length=200, null=True)),
                ('c4', models.CharField(blank=True, max_length=200, null=True)),
                ('c5', models.CharField(blank=True, max_length=200, null=True)),
                ('c6', models.CharField(blank=True, max_length=200, null=True)),
                ('c7', models.CharField(blank=True, max_length=200, null=True)),
                ('c8', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
